<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Home\htmlpage.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\Home\htmlpage.cshtml" />
    <None Include="Views\UserMenuAuthorization\index.cshtml" />
    <None Include="wwwroot\lib\bootstrap-datepicker\bootstrap-datepicker.min.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="X.PagedList" Version="10.5.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Log\" />
  </ItemGroup>

</Project>
